SPOOL solution4
SET SERVEROUTPUT ON
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON
/*sib979*/
/*Task 4*/
CREATE OR REPLACE FUNCTION TOTAL_ORDERS(companyName IN VARCHAR) RETURN
NUMBER IS
    totalOrders NUMBER;
BEGIN
    SELECT count(*)
    INTO totalOrders
    FROM ORDERS
    JOIN CUSTOMER ON ORDERS.CUSTOMER_CODE = CUSTOMER.CUSTOMER_CODE
    WHERE COMPANY_NAME = companyName;

    RETURN(totalOrders);
END TOTAL_ORDERS;
/

SELECT COMPANY_NAME, ADDRESS, TOTAL_ORDERS(COMPANY_NAME)
FROM CUSTOMER
WHERE TOTAL_ORDERS(COMPANY_NAME) > 2 AND TOTAL_ORDERS(COMPANY_NAME) < 6;